Trex Presentation/MVCRecap/MVCRecap/Models/AirlineModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCRecap.Models
{
    public class AirlineModel
    {
        [Key]
        public int AirID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public bool available { get; set; }
    }
}

Trex Presentation/MVCRecap/MVCRecap/Models/DestinationModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCRecap.Models
{
    public class DestinationModel
    {
        [Key]
        public int DestID { get; set; }
        [Required]
        public string City { get; set; }
    }
}

Trex Presentation/MVCRecap/MVCRecap/Models/ErrorViewModel.cs
using System;

namespace MVCRecap.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Trex Presentation/MVCRecap/MVCRecap/Models/TicketModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCRecap.Models
{
    public class TicketModel
    {
        [Key]
        public int TicketID { get; set; }
        [Required]
        public string Airline { get; set; }
        [Required]
        public string Origin { get; set; }
        [Required]
        public string Destination { get; set; }
        [Required]
        [DataType(DataType.Currency)]
        public double Cost { get; set; }
        public DateTime Date { get; set; }
    }
}

Trex Presentation/MVCRecap/MVCRecap/Controllers/AirlineController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCRecap.Data;
using MVCRecap.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCRecap.Controllers
{
    public class AirlineController : Controller
    {
        private readonly ApplicationDBContext _context;

        public AirlineController(ApplicationDBContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var airline = await _context.AirlineModel.ToListAsync();
            return View(airline);
        }

    }
}

Trex Presentation/MVCRecap/MVCRecap/Controllers/CityController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCRecap.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCRecap.Controllers
{
    
    public class CityController : Controller
    {

        private readonly ApplicationDBContext _context;

        public CityController(ApplicationDBContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var cityList = await _context.DestinationModel.ToListAsync();
            return View(cityList);
        }

    }
}

Trex Presentation/MVCRecap/MVCRecap/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCRecap.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MVCRecap.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Trex Presentation/MVCRecap/MVCRecap/Controllers/TicketController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCRecap.Data;
using MVCRecap.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCRecap.Controllers
{
    public class TicketController : Controller
    {
        private readonly ApplicationDBContext _context;

        public TicketController(ApplicationDBContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var TikList = await _context.TicketModel.ToListAsync();
            return View(TikList);
        }
        public IActionResult Create()
        {
            List<AirlineModel> tempList = new();
            tempList = (from item in _context.AirlineModel
                           select item).ToList();

            List<AirlineModel> airlineList = new();


            foreach (var item in tempList)
            {
                if (item.available == true)
                {
                    airlineList.Add(item);
                }
            }
            tempList = null;

            List<DestinationModel> cityList = new List<DestinationModel>();
            cityList = (from item in _context.DestinationModel
                        select item).ToList();

            ViewBag.ListofAirlines = airlineList;
            ViewBag.ListofCities = cityList;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TicketModel ticket)
        {

            if (ModelState.IsValid)
            {
                _context.TicketModel.Add(ticket);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
                return View(ticket);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            var ticket = await _context.TicketModel.FindAsync(id);
            if (id == null)
            {
                return NotFound();
            }

            List<AirlineModel> tempList = new();
            tempList = (from item in _context.AirlineModel
                        select item).ToList();

            List<AirlineModel> airlineList = new();


            foreach (var item in tempList)
            {
                if (item.available == true)
                {
                    airlineList.Add(item);
                }
            }
            tempList = null;

            List<DestinationModel> cityList = new List<DestinationModel>();
            cityList = (from item in _context.DestinationModel
                        select item).ToList();

            ViewBag.ListofAirlines = airlineList;
            ViewBag.ListofCities = cityList;
            return View(ticket);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(TicketModel ticket)
        {
            if (ModelState.IsValid)
            {
                _context.TicketModel.Update(ticket);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
                return View(ticket);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            var ticket = await _context.TicketModel.FindAsync(id);
            if (id == null)
            {
                return NotFound();
            }
            return View(ticket);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var ticket = await _context.TicketModel.FindAsync(id);
            if (ModelState.IsValid)
            {
                _context.TicketModel.Remove(ticket);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
                return RedirectToAction("Index");
        }
    }
}

Trex Presentation/MVCRecap/MVCRecap/Views/Airline/Index.cshtml
@model IEnumerable<MVCRecap.Models.AirlineModel>
@{
    ViewData["Title"] = "Airlines";
    <link rel="stylesheet" href="~/css/TrexStyle.css" />
}
<!DOCTYPE html>
<html>
<body class="custom">
    <h1 style="margin-bottom: 50px">Available Airlines</h1>

    <div class="table-responsive">
        <table class="table">
            <thead style="background-color: deepskyblue; border-collapse: collapse">
                <tr>
                    <th style="border-bottom: 2px solid  black">
                        <b style="font-size:larger">@Html.DisplayNameFor(model => model.Name)</b>
                    </th>
                    <th style="border-bottom: 2px solid black; text-align: center">
                        <b style="font-size:larger">Availability</b>
                    </th>
                </tr>
            </thead>
            <tbody style="background-color: lightskyblue">
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <b>@Html.DisplayFor(modelItem => item.Name)</b>
                        </td>
                        <td style="text-align:center">
                            <b> @Html.DisplayFor(modelItem => item.available)</b>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>

Trex Presentation/MVCRecap/MVCRecap/Views/City/Index.cshtml
@model IEnumerable<MVCRecap.Models.DestinationModel>

@{
    ViewData["Title"] = "Cities";
    <link rel="stylesheet" href="~/css/TrexStyle.css" />
}
<!DOCTYPE html>
<html>
<body class="custom">
    <h1 style="margin-bottom: 50px">Available Cities</h1>


    <table class="table" style="border-collapse: collapse">
        <thead style="background-color: deepskyblue">
            <tr>
                <th style="border-bottom: 2px solid  black">
                   <b style="font-size:larger">@Html.DisplayNameFor(model => model.City)</b>
                </th>
            </tr>
        </thead>
        <tbody style="background-color: lightskyblue">
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                       <b>@Html.DisplayFor(modelItem => item.City)</b>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>

Trex Presentation/MVCRecap/MVCRecap/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
    <link rel="stylesheet" href="~/css/TrexStyle.css"/>
}
<!DOCTYPE html>
<html>
<head>
    <!--<link rel="stylesheet" href="~/css/TrexStyle.css" />-->
</head>
<body class="custom">
    <h1>@ViewData["Title"]</h1>
    <p><b style="font-size: xx-large">VacaPlanner is a website that helps you plan your next vacation!</b></p>
    <ul>
        <li><b style="color: limegreen; font-size:x-large">Check Availability</b></li>
        <li><b style="color: darkblue; font-size: x-large">Book Flights</b></li>
        <li><b style="color: goldenrod; font-size: x-large">Best Deals!</b></li>
    </ul>
</body>
</html>



Trex Presentation/MVCRecap/MVCRecap/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "VacaPlanner";
}

<div class="text-center">
    <h1 class="display-4">Welcome!</h1>
    <p>Plan your vacations with <a href="https://localhost:44384/Home/About" style="color: black"><b>VacaPlanner.com</b></a></p>
    <img src="https://img.search.brave.com/_Mc_AmPxfVviQCP5hVI1bkH-ZBvGuraYM30tcwxRnmk/rs:fit:480:270:1/g:ce/aHR0cHM6Ly9tZWRp/YS5naXBoeS5jb20v/bWVkaWEvNVhDV0xI/Nm92bHNpSVNwVTJV/L2dpcGh5LmdpZg.gif" style="width: 600px; height: 450px"/>
</div>

Trex Presentation/MVCRecap/MVCRecap/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AirLine</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AirLine Management System</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Airline" asp-action="Index">Airlines</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Index">Cities</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ticket" asp-action="Index">Ticket</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Trex Presentation/MVCRecap/MVCRecap/Views/Ticket/Create.cshtml
@model MVCRecap.Models.TicketModel

@{
    ViewData["Title"] = "Create";
    <link rel="stylesheet" href="~/css/TrexStyle.css" />
}
<!DOCTYPE html>
<html>
<body class="custom">
    <h1>Create</h1>

    <h4>TicketModel</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Airline" class="control-label" style="font-weight:bold"></label>
                    <select asp-for="Airline"
                            class="form-control"
                            asp-items="@(new SelectList(@ViewBag.ListofAirlines,"Name","Name"))"></select>
                    <span asp-validation-for="Airline" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Origin" class="control-label" style="font-weight:bold"></label>
                    <select asp-for="Origin"
                            class="form-control"
                            asp-items="@(new SelectList(@ViewBag.ListofCities,"City","City"))"></select>
                    <span asp-validation-for="Origin" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Destination" class="control-label" style="font-weight:bold"></label>
                    <select asp-for="Destination"
                            class="form-control"
                            asp-items="@(new SelectList(@ViewBag.ListofCities,"City","City"))"></select>
                    <span asp-validation-for="Destination" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Cost" class="control-label" style="font-weight:bold"></label>
                    <input asp-for="Cost" class="form-control" />
                    <span asp-validation-for="Cost" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Date" class="control-label" style="font-weight:bold"></label>
                    <input asp-for="Date" class="form-control" />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <a class="btn btn-warning" asp-action="Index">Back to List</a>
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </form>
        </div>
    </div>
</body>
</html>
@section Scripts {

    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Trex Presentation/MVCRecap/MVCRecap/Views/Ticket/Delete.cshtml
@model MVCRecap.Models.TicketModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3 style="margin-bottom: 25px">Are you sure you want to delete this?</h3>
<div>
    <h4>Ticket Information</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Airline)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Airline)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Origin)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Origin)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Destination)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cost)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cost)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <a class="btn btn-primary" asp-action="Index">No</a>
        <input type="hidden" asp-for="TicketID" />
        <input class="btn btn-danger" type="submit" value="Yes" />
    </form>
</div>

Trex Presentation/MVCRecap/MVCRecap/Views/Ticket/Edit.cshtml
@model MVCRecap.Models.TicketModel

@{
    ViewData["Title"] = "Edit";
    <link rel="stylesheet" href="~/css/TrexStyle.css"/>
}
<!DOCTYPE html>
<html>

    <body class="custom">
    <h1>Edit</h1>

    <h4>TicketModel</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="TicketID" />
                <div class="form-group">
                    <label asp-for="Airline" class="control-label" style="font-weight:bold"></label>
                    <select asp-for="Airline"
                            class="form-control"
                            asp-items="@(new SelectList(@ViewBag.ListofAirlines,"Name","Name"))"></select>
                    <span asp-validation-for="Airline" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Origin" class="control-label" style="font-weight:bold"></label>
                    <select asp-for="Origin"
                            class="form-control"
                            asp-items="@(new SelectList(@ViewBag.ListofCities,"City","City"))"></select>
                    <span asp-validation-for="Origin" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Destination" class="control-label" style="font-weight:bold"></label>
                    <select asp-for="Destination"
                            class="form-control"
                            asp-items="@(new SelectList(@ViewBag.ListofCities,"City","City"))"></select>
                    <span asp-validation-for="Destination" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Cost" class="control-label" style="font-weight:bold"></label>
                    <input asp-for="Cost" class="form-control" />
                    <span asp-validation-for="Cost" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Date" class="control-label" style="font-weight:bold"></label>
                    <input asp-for="Date" class="form-control" />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <a class="btn btn-warning" asp-action="Index">Back to List</a>
                    <input type="submit" value="Update" class="btn btn-success" />
                </div>
            </form>
        </div>
    </div>

    </body>
</html>
@section Scripts {

    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Trex Presentation/MVCRecap/MVCRecap/Views/Ticket/Index.cshtml
@model IEnumerable<MVCRecap.Models.TicketModel>

@{
    ViewData["Title"] = "Index";
    <link rel="stylesheet" href="~/css/TrexStyle.css" />
}
<!DOCTYPE html>
<html>
<body class="custom">
    <h1 style="margin-bottom: 50px">Active Tickets</h1>

    <p>
        <a class="btn btn-success" asp-action="Create">Create New</a>
    </p>

    <table class="table">
        <thead style="background-color: deepskyblue; border-collapse: collapse; border-bottom: 1px solid black">
            <tr>
                <th>
                    <b> @Html.DisplayNameFor(model => model.Airline)</b>
                </th>
                <th>
                    <b> @Html.DisplayNameFor(model => model.Origin)</b>
                </th>
                <th>
                    <b> @Html.DisplayNameFor(model => model.Destination)</b>
                </th>
                <th>
                    <b> @Html.DisplayNameFor(model => model.Cost)</b>
                </th>
                <th>
                    <b> @Html.DisplayNameFor(model => model.Date)</b>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody style="background-color: lightskyblue">
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <b>@Html.DisplayFor(modelItem => item.Airline)</b>
                    </td>
                    <td>
                        <b> @Html.DisplayFor(modelItem => item.Origin)</b>
                    </td>
                    <td>
                        <b> @Html.DisplayFor(modelItem => item.Destination)</b>
                    </td>
                    <td>
                        <b> @Html.DisplayFor(modelItem => item.Cost)</b>
                    </td>
                    <td>
                        <b> @Html.DisplayFor(modelItem => item.Date)</b>
                    </td>
                    <td>
                        <a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.TicketID">Edit</a> &nbsp;
                        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.TicketID">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>